# AntiCheat System Configuration

# Discord integration
discord:
  link: "https://discord.gg/your-discord-link"
  webhook: "https://discord.com/api/webhooks/your-webhook-id/your-webhook-token"

# Alert settings
alerts:
  cooldown:
    autoclick: 1.0
    reach: 1.0
    speed: 1.0
    killaura: 1.0
    fly: 1.0
    aimbot: 1.0

# Check configurations
checks:
  autoclick:
    enabled: true
    max_autoclick_alerts: 2
    max_autoclick_ban: 3
    ping_threshold: 100
    violation_threshold: 3
  
  reach:
    enabled: true
    max_reach_alerts: 3.5
    max_reach_ban: 4.5
    violation_threshold: 3
  
  speed:
    enabled: true
    max_speed: 10
    max_speed_ban: 15
    ping_threshold: 100
    violation_threshold: 3
  
  killaura:
    enabled: true
    max_targets: 3
    max_rotation_speed: 40
    violation_threshold: 3
  
  fly:
    enabled: true
    max_air_time: 60
    violation_threshold: 5
    ignore_sprint_jump: true
  
  aimbot:
    enabled: true
    max_variance: 5.0
    violation_threshold: 3

# Punishment settings
punishments:
  default_ban_duration: "30d"
  ban_message: "&7Has sido BANEADO\nRazón: &6{reason}\n&7Expira en: &6{time}\n&7Si deseas apelar el ban: &6{discord}"
  
# Debug setting
debug:
  enabled: false
  log_level: 1